name: Updater

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/10 * * * *'

jobs:
  updater:
    name: Updater
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Checkout rules
      run: git submodule update --init --force --recursive --depth=1

    - name: Update
      run: cd rules && git pull origin master

    - name: Commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add .
        if [ "$(git status | grep "nothing to commit" | wc -l)" = "0" ]; then
          git config --global user.name "Updater"
          git config --global user.email actions@github.com
          git commit -m "Update $(date -u)"

          OWNER=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
          header=$(echo -n "${OWNER}:${GITHUB_TOKEN}" | base64)
          git -c http.extraheader="AUTHORIZATION: basic $header" push origin HEAD:master
        fi